version: "3.7"
services:
  postgres:
    container_name: fab-postgres
    image: postgres:14
    restart: unless-stopped
    env_file: .env
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pguserpassword
      POSTGRES_USER: pguser
    ports:
      - 5432:5432
  mongo:
    container_name: fab-mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: app
    ports:
      - 27017:27017
